<?php
/**
 * Created by PhpStorm.
 * User: fatfish
 * Date: 13/4/18
 * Time: 3:41 PM
 */

namespace fatfish\importer\records;
use Craft;
use craft\db\ActiveRecord;

class FeedRecord extends ActiveRecord
{
    public static function tableName():string
    {
        return '{{%importer_feeds}}';
    }
    public static function find()
    {
        return parent::find(); // TODO: Change the autogenerated stub
    }
}