<?php
/**
 * Created by PhpStorm.
 * User: fatfish
 * Date: 19/4/18
 * Time: 5:13 PM
 */

namespace fatfish\importer\models;


use craft\base\Model;

class FeedMappingModel extends Model
{

    public $id;
    public $entries_field;
    public $mapped_field;
    public $critearea;
    public $feed_type;

    public function rules()
    {
        return [
            ['id','integer'],
            ['entries_field','string'],
            ['mapped_field','string'],
            ['critearea','string'],
            ['feed_type','string'],

        ]; // TODO: Change the autogenerated stub
    }


}